version: "3"
services:
  eleventy:
    image: node:18-slim
    user: node
    volumes:
      - ${PWD}/node_modules
      - ${PWD}:/app
    working_dir: /app
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - GIST_TOKEN=${GH_GIST_TOKEN}
      - ELEVENTY_ENV=development
    #   - DEBUG=Eleventy*
    ports:
      - 8080:8080
    command: /bin/bash -c "npm install && npm start"
